name: SteveNova
version: "${version}"
api-version: "${apiVersion}"
authors: [ "StudioCode", "ByteZ1337", "Javahase", "Hužva" ]
website: "https://github.com/huzvanec/SteveNova/"
loader: xyz.xenondevs.nova.NovaLoader
bootstrapper: xyz.xenondevs.nova.NovaBootstrapper
main: xyz.xenondevs.nova.Nova
load: STARTUP
provides: [ Nova ]

dependencies:
  server:
    WorldGuard:
      required: false
    GriefPrevention:
      required: false
    PlotSquared:
      required: false
    ProtectionStones:
      required: false
    Towny:
      required: false
    QuickShop:
      required: false
    Residence:
      required: false
    Vault:
      required: false
    ItemsAdder:
      required: false
    Nexo:
      required: false
    MMOItems:
      required: false
    AuthMe:
      required: false
    FastAsyncWorldEdit:
      required: false
    WorldEdit:
      required: false
    LuckPerms:
      required: false

permissions:
  nova.command.*:
    description: Gives access to all Nova commands.
    children:
      - nova.command.give
      - nova.command.debug
      - nova.command.items
      - nova.command.advancedTooltips
      - nova.command.waila
      - nova.command.renderDistance
      - nova.command.nvrecipe
      - nova.command.nvusage
      - nova.command.addons
      - nova.command.resourcePack
      - nova.command.reload
      - nova.command.enchant
      - nova.command.unenchant
  nova.command.items:
    description: Allows players to open the nova items menu.
    default: true
  nova.command.nvrecipe:
    description: Allows players to use the /nvrecipe command.
    default: true
  nova.command.nvusage:
    description: Allows players to use the /nvusage command.
    default: true
  nova.command.renderDistance:
    description: Allows players to configure their armor stand render distance.
    default: true
  nova.command.advancedTooltips:
    description: Allows players to toggle advanced tooltips for Nova items.
    default: true
  nova.command.waila:
    description: Allows players to toggle the waila overlay on and off.
    default: true
  nova.command.give:
    description: Allows players to cheat nova items using /nova give.
  nova.command.debug:
    description: Allows the usage of the /nova debug command.
  nova.command.addons:
    description: Allows players to use the /nova addons command.
  nova.command.resourcePack:
    description: Allows players to create and reupload the resource pack.
  nova.command.reload:
    description: Allows players to reload configs and recipes.
  nova.command.enchant:
    description: Allows players to enchant items
  nova.command.unenchant:
    description: Allows players to unenchant items
  nova.misc.updateReminder:
    description: Players with this permission will be reminded if a new version is available
    default: false
  nova.misc.bypassTileEntityLimits:
    description: Players with this permission will be able to bypass the tile entity limits set in the config.
    default: false
  nova.misc.resourcePack.bypass.force:
    description: Players with this permission will not be forced to accept the resource pack, assuming the config option is enabled.
    default: false
  nova.misc.resourcePack.bypass.prompt:
    description: Players with this permission will not be prompted to accept the resource pack, assuming the config option is enabled.
    default: false